keys:
  - &pub age1qclnc2pvscjkldf450zq2qhm8zfgr95cuhe9ajqkkvg892snsyustt0qrx
  - &age age1zw0dc65l5l6rn8upx002sssrx9e5gnfsm67kqp8m9wag5j0s9cdq56cuar
  - &hosts:
    - &pi1 age1juv423mvgxx4t8k8t6susnp7mtc0wmsauynkx83jtzxzxcl9qc5sfdt6pl
    - &vm-srv age1c3vce4p946e8wpz0sl3tk80dv0vjk49f4updvrj3a5nrspekkg0q7kwefl
  - &prox
    - &srv1 age16hxfkwg4jh4sducj458anwwh35cmdks9jvgmxm4ar5zh83clcgss5uy02c
    - &git age1vjmttuq2z8rtzgmjvqqr9ms2zv007wpapffcy02uxg8807u9r99sdxg0hj
creation_rules:
  - path_regex: secrets/git.yaml$
    key_groups:
    - age:
      - *srv1
      - *git
      - *pub
  - path_regex: secrets/*.*.yaml$
    key_groups:
    - age:
      - *pub
      - *age
      - *pi1
      - *vm-srv
      - *srv1
